blog/urls.py
from django.urls import path, include

from blog.models import Post
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    PostCategoryView,
    PostAddLike,
    PostAddComment,
)

app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('<int:pk>', PostDetailView.as_view(), name='post-detail'),
    path('edit/<int:pk>', PostUpdateView.as_view(), name='post-edit'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='post-delete'),
    path('create/', PostCreateView.as_view(), name='post-create'),
    path('category/<str:cats>/', PostCategoryView, name='post-category'),

    # ajax urls
    path('userlike/', PostAddLike, name='post-user-like'),
    path('usercomment/', PostAddComment, name='post-user-comment'),
]

# handler404 = 'blog.views.errorpage'
# handler500 = 'blog.views.errorpage'

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import HomePageView, SubmitContact
from django.conf import settings
from django.conf.urls.static import static

app_name = 'pages'
urlpatterns = [
    path('contact_submit/', SubmitContact, name='contact-submit'),
    path('', HomePageView.as_view(), name='home'),
]

blog/models.py
from django.contrib import auth
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from datetime import datetime, date
from ckeditor.fields import RichTextField
import os

#  Receive the pre_delete signal and delete the file associated with the model instance.
from django.db.models.signals import pre_delete, post_delete
from django.dispatch.dispatcher import receiver

class Category(models.Model):
    name = models.CharField(max_length=225)
    
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=255)
    header_image = models.ImageField(null=True, blank=True, upload_to="uploads/")
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    # body = models.TextField()
    body = RichTextField(blank=True, null=True)
    # category = models.CharField(max_length=64, default="Uncategorized")
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(get_user_model(), related_name='blog_posts')
    

    def total_comments(self):
        return self.comments.count()

    def total_likes(self):
        return self.likes.count()
    
    def __str__(self):
        return self.title + ' | ' + str(self.author)
    
    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={"pk":  self.pk})

    def delete(self):
        self.header_image.delete()
        super(Post, self).delete()

class Comment(models.Model):
    post = models.ForeignKey(
        Post, 
        on_delete=models.CASCADE,
        related_name='comments',
        )
    comment = models.TextField()
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={"pk":  self.pk})
    

def _delete_file(path):
#    """ Deletes file from filesystem. """
   if os.path.isfile(path):
       os.remove(path)

@receiver(models.signals.post_delete, sender=Post)
def delete_file(sender, instance, *args, **kwargs):
    """ Deletes image files on `post_delete` """
    if instance.header_image:
        _delete_file(instance.header_image.path)

blog/forms.py
from django import forms
from .models import Post, Category, Comment
from django.contrib.auth import get_user_model

category_choices = Category.objects.all().values_list('name', 'name')
choices = []
for item in category_choices:
    choices.append(item)

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title', 
            'body',
            'category',
            'header_image'
        ]
        
        labels = {
            "title": "Post Title",
            "body": "Write a Content.."
        }
        
        widgets = {
            'title': forms.TextInput(attrs={'class': 'contact_input'}),
            'body': forms.Textarea(attrs={'class': 'contact_input', 'rows': '10'}),
            'category': forms.Select(choices=choices, attrs={'class': 'contact_input'}),
            'header_image': forms.FileInput(attrs={'class': 'contact_input'}),
        }
        
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        return super(PostCreateForm, self).__init__(*args, **kwargs)
    
        
    def save(self, *args, **kwargs):
        kwargs['commit']=False
        obj = super(PostCreateForm, self).save(*args, **kwargs)
        if self.request:
            obj.author = self.request.user
            obj.save()
        return obj 
    
    def clean_title(self):
        title = self.cleaned_data.get('title')
        return title
        
    def clean_body(self):
        body = self.cleaned_data.get('body')
        return body
    
    # def clean_tag(self):
    #     tag = self.cleaned_data.get('tag')
    #     return tag
    
    def clean_category(self):
        category = self.cleaned_data.get('category')
        return category
    
    def clean_header_image(self):
        header_image = self.cleaned_data.get('header_image')
        return header_image
    
class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title', 
            'body',
            'category',
            # 'header_image' temporarily remove header image field on update post form
        ]
        
        labels = {
            "title": "Post Title",
            "body": "Write a Content.."
        }
        
        widgets = {
            'title': forms.TextInput(attrs={'class': 'contact_input'}),
            'body': forms.Textarea(attrs={'class': 'contact_input', 'rows': '10'}),
            'category': forms.Select(choices=choices, attrs={'class': 'contact_input'}),
            # 'header_image': forms.FileInput(attrs={'class': 'contact_input'}),
        }

class PostAddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'comment', 
        ]
        
        labels = {
            "comment": "Write a Comment.."
        }
        
        widgets = {
            'comment': forms.Textarea(attrs={'class': 'contact_input', 'rows': '2'}),
        }

blog/views.py
# rendering, get object list and redirect classes, reverse for url utility funcs
from django.contrib import auth
from django.contrib.auth.models import User
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.http import Http404, HttpResponseBadRequest, JsonResponse, request
from django.db.models import Count
from django.utils import timezone, dateformat


import json, datetime
from django.core import serializers

# view functions
from django.views import View
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)

# models
from .models import Post, Category, Comment
from django.db.models import F

#form
from .forms import PostCreateForm, PostUpdateForm, PostAddCommentForm

# instead importing user, import the custom user from abstract user class we created
from django.contrib.auth import get_user_model

#mixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

class PostListView(ListView):
    model = Post
    template_name = 'post_list.html'
    ordering = ['-date']
    
    def get_context_data(self, *args, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        context['categories'] = get_category_list()
        context['recent_posts'] = get_recent_posts()
        return context
        
    
class PostDetailView(DetailView):
    model = Post
    template_name = 'post_details.html'
    form_class = PostAddCommentForm
    
    def get_context_data(self, *args, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)

        post_object = get_object_or_404(Post, id=self.kwargs['pk'])
        liked = False

        if post_object.likes.filter(id=self.request.user.id).exists():
            liked = False
        else:
            liked = True
            
        context['categories'] = get_category_list()
        context['total_likes'] = post_object.total_likes()
        context['isLiked'] = liked
        context['total_comments'] = post_object.total_comments()
        # print(context)
        return context
    
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostCreateForm
    template_name = 'post_create.html'
    # __all__ fills up all inputs on models
    
    def get_form_kwargs(self):
        # Ensure the current `request` is provided to NonProfitCreateForm.
        kwargs = super(PostCreateView, self).get_form_kwargs()
        kwargs.update({ 'request': self.request })
        return kwargs

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostUpdateForm
    template_name = 'post_update.html'
    
    
    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user
    
class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('blog:post-list')
    
    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user
    
def PostCategoryView(request, cats):
    category_posts = Post.objects.select_related('category').annotate(category_name=F('category__name')).filter(category_name__iexact=cats).order_by('-date')
    count_posts = category_posts.count()
    
    if count_posts == 0:
        return Http404
    
    context = {
        'category_name': cats,
        'category_posts': category_posts,
        'post_count': count_posts,
        'recent_posts': get_recent_posts(),
        'categories': get_category_list(),
    }
    
    return render(request, 'post_categories.html', context)

def PostAddLike(request):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if is_ajax:
        if request.method == 'POST':
            data = json.load(request)
            like_data = data.get('payload')
            post_id = like_data['post_id']
            postobj = get_object_or_404(Post, id=post_id)

            liked = False # to pass on context to serve as an identifier if post is liked
            if postobj.likes.filter(id=request.user.id).exists():
                postobj.likes.remove(request.user)
                liked = False
            else:
                postobj.likes.add(request.user)
                liked = True
            
            total_likes = postobj.total_likes()
            return JsonResponse({
                'status': 'Contact Submitted!',
                'isLiked': liked,
                'total_likes': total_likes,
                })
        return JsonResponse({'status': 'Invalid request'}, status=400)
    else:
        return HttpResponseBadRequest('Invalid request')
    
    # return HttpResponseRedirect(reverse('blog:post-detail', kwargs={"pk": pk}))

def PostAddComment(request):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if is_ajax:
        if request.method == 'POST':
            data = json.load(request)
            comment_data = data.get('payload')
            post_id = comment_data['post_id']
            post_comment = comment_data['post_comment']
            # post id, comment text, author 
            post_obj = get_object_or_404(Post, id=post_id)
            Comment.objects.create(
                post=post_obj, 
                comment=post_comment, 
                author=request.user,
                )
                
            # query = Post.objects.filter(pk=18).values('comments')
            now = dateformat.format(timezone.now(), "M. d,Y, H:i a")
            total_comments = post_obj.total_comments()
            return JsonResponse({
                'status': 'comment added',
                'body': post_comment,
                'date': now,
                'author': str(request.user),
                'total_comments': total_comments
                })
        return JsonResponse({'status': 'Invalid request'}, status=400)
    else:
        return HttpResponseBadRequest('Invalid request')


def get_category_list():
    # category bar with number of posts
    categories_list = Category.objects.annotate(posts_count=Count('post'))
    return categories_list

def get_recent_posts():
    # recent post with limit of 3 recent post
    recentposts_list = Post.objects.all().order_by('-date')[:3]
    return recentposts_list
    
        

blog/templates/blog_header.html
<header class="header" id="header">
    <nav class="nav container">
        <a href="{% url 'pages:home' %}" class="nav_logo">Jarvis </a>
        <div class="nav_menu" id="nav-menu">
            <ul class="nav_list grid">
                <li class="nav_item">
                   <a href="{% url 'pages:home' %}" class="nav_link">
                        <i id="active_starter" class="uil uil-home nav_icon "></i> Home
                    </a>
                </li>
                <li  class="nav_item">
                    <a href="{% url 'blog:post-list' %}" class="nav_link">
                        <i class="uil uil-document-layout-left nav_icon active-link"></i> Blog
                    </a>
                </li>
            </ul>

            <i class="uil uil-times nav_close " id="nav-close"></i>
        </div>

        <div class="nav_btns">
            <!-- change theme -->
            <i class="uil uil-moon change_theme" id="theme-button"></i>

            <div class="nav_toggle" id="nav-toggle">
                <i class="uil uil-apps"></i>
            </div>
        </div>
    </nav>
</header>

blog/templates/post_categories.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Blog {% endblock title %}

{% block content %}
    <section class="blog section">
        <h2 class="section_title"> {{ category_name }}</h2>
        <span class="section_subtitle">{{ post_count }} Post{{ post_count|pluralize }}</span>
        
        <div class="container blog_container grid">
            <div class="post_data">
                <div class="post_items grid">
                    <!-- <p>{{ post_count }}</p> -->
                    {% for post in category_posts %}
                    <div class="post_item">
                        <div class="post_item_img">
                            <a class="post_list_links" href="{{ post.get_absolute_url }}">
                                {% if post.header_image %}
                                <img class="" src="{{ post.header_image.url }}" alt="{{ post.header_image }}" />
                                {% else %}
                                <img class="" src="{% static 'img/defaults/noimage.png' %}" alt="noimage" >
                                {% endif %}
                            </a>
                        </div>
                        <div class="post_item_content">
                            <h1><a class="post_list_links" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h1>
                            <h4>{{ post.author }}</h4>
                            <p class="post_item_content_body">{{ post.body|truncatewords:40|safe }}</p>
                            <p class="post_item_content_date">posted on: {{ post.date|date:"SHORT_DATE_FORMAT" }}</p>
                        </div>
                    </div>
                    {% endfor %} 
                </div>
            </div>
            <div class="post_sidebar"> 
                <div class="sidebar_recent_posts">
                    <div class="recent_posts_header">
                        <h3 class="">Recent Posts</h3>
                    </div>
                    
                    {% for post in recent_posts %}
                    <div class="recent_posts_item grid">
                        <div class="rp_item_thumbnail">
                            <a href="{{ post.get_absolute_url }}">
                                {% if post.header_image %}
                                <img class="" src="{{ post.header_image.url }}" alt="{{ post.header_image }}" />
                                {% else %}
                                <img class="" src="{% static 'img/defaults/noimage.png' %}" alt="noimage" >
                                {% endif %}
                            </a>
                        </div>
                        <div class="rp_details">
                            <a href="{{ post.get_absolute_url }}">
                                <p class="rp_item_date">{{ post.date|date:"D, M d, Y"  }}</p>
                                <p class="rp_item_title">{{ post.title|truncatewords:3|safe }}</p>
                            <a href=""></a>
                        </div>
                    </div>
                    {% endfor %}
                
                </div>

                <div class="sidebar_categories">
                    <div class="categories_header">
                        <h3 class="">Categories</h3>
                    </div>

                    <div class="categories_links grid">
                        <ul>
                            {% for category in categories %}
                            <li>
                                <a class="categories_link" href="{% url 'blog:post-category' category.name %}">
                                    <div class="categories_item">
                                        <h4>{{ category.name }}</h4>
                                        <span class="count_posts_badge">{{ category.posts_count }}</span>
                                    </div>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

blog/templates/post_create.html
{% extends 'base.html' %}

{% block title %} Create Post {% endblock title %}

{% block content %}

<section class="blog section">
    <h2 class="section_title post_detail_title"> Create Blog Post</h2>
    <!-- <span class="section_subtitle"></span> -->
    
    <div class="container blog_container grid">
        <form method="post" enctype="multipart/form-data">
            <div class=" grid">
                {% csrf_token %}
                {{form.media}}
                {% for field in form %}
                    <div class="contact_content">
                        <label class="contact_label">{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
                <!-- {{ form.as_p }}-->
                <div class="">
                    <input class="button button--flex contact_submit" type="submit" value="Create Post">
                </div> 
            </div>
        </form>
    </div>
</section>


{% endblock content %}

blog/templates/post_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Delete Post {% endblock title %}

{% block content %}
<section class="blog section">
    <h2 class="section_title post_detail_title"> {{ post.title }}</h2>
    <!-- <span class="section_subtitle"></span> -->
    
    <div class="container blog_container grid">
        <form method="post">
            {% csrf_token %}
            <h3>Are you sure you want to delete <u>{{ post.title }}</u>?</h3>
            <br>
            <div class="">
                <input class="button button--flex contact_submit" type="submit" value="Confirm">
            </div> 
        </form>
    </div>
</section>
{% endblock content %}

blog/templates/post_details.html
{% extends 'base.html' %} {% load static %}
 {% block title %} {{ post.title }} {% endblock title %} 

 {% block content %}
<section class="blog section">
    <div class="container">
        <h2 class="section_title post_detail_title"> {{ post.title }}</h2>
        <span class="section_subtitle ">by {{ post.author }} </span>
        
    </div>
    <div class="container blog_container grid">
        <div class="post_data">
            <div class="post_items">
                <div class="post_item post_detail_item grid">
                    <!-- image here -->
                    <div class="post_item_img">
                        <!-- <a class="post_list_links" href="{{ post.get_absolute_url }}"> -->
                        {% if post.header_image %}
                        <img class="" src="{{ post.header_image.url }}" alt="{{ post.header_image }}" /> {% else %}
                        <img class="" src="{% static 'img/defaults/noimage.png' %}" alt="noimage"> {% endif %}
                        <!-- </a> -->
                    </div>
                    <div class="post_item_content">
                        <p>{{ post.body|safe }}</p>
                        <p><b>posted on: {{ post.date|date:"SHORT_DATE_FORMAT" }}</b></p>
                    </div>
                </div>
            </div>
            {% if user.is_authenticated %}
            <div class="post_actions">
                <a href="{% url 'blog:post-edit' post.pk %}" class="button button_nm button_outline button--flex contact_submit">Edit</a>
                <a href="{% url 'blog:post-delete' post.pk %}" class="button button_nm button--flex contact_submit">Delete</a>
            </div>
            {% endif %}

            

                {% if user.is_authenticated %}
        <form method="post" class="" id="post-like-submit">
            <div class="post_like container">
            <p class="container_title" id="total-likes">{{ post.total_likes }} Like{{ post.total_likes|pluralize }}</p>

            <input type="hidden" value="{% url 'blog:post-user-like' %}" id="post-like-url">
            <!-- {% csrf_token %} -->
            <input type="hidden" value="{{ post.id }}" id="post-id">

            {% if isLiked %}
                <button id="post-like-btn" type="submit" class="button button_nm button--flex contact_submit" ><i class="uil uil-thumbs-up "></i>&nbsp; Like</button>
            {% else %}
                <button id="post-like-btn" type="submit" class="button button_nm button--flex contact_submit" ><i class="uil uil-thumbs-down "></i> &nbsp; UnLike</button> 
            {% endif %}

            </div>
        </form>
        {% endif %}

            <div class="post_comments">
                <div class="comment_header">
                    <p class="container_title " id="total-comments">{{ total_comments }} Comment{{ total_comments|pluralize }}</p>
                </div>
                <hr>
                <div id="comments-wrapper" class="comments_wrapper">
                    {% for comment in post.comments.all reversed  %}
                        <div class="comment_item">
                            <p class="comment_author">{{ comment.author }} <span class="comment_timestamp">on {{ comment.timestamp }}</span></p>
                            <p class="comment_detail">{{ comment }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
            
            {% if user.is_authenticated %}
                <div class="post_comments_actions container">
                    <form id="form-add-comment" method="post">
                        <input type="hidden" value="{% url 'blog:post-user-comment' %}" id="post-comment-url">
                        <input type="hidden" value="{{ post.id }}" id="post-id">
                        <textarea maxlength="150" required name="" id="post-comment" class="contact_input add_comments_data" placeholder="Write A Comment.. " cols="30" rows="3"></textarea>
                        <button class="button button_nm button--flex add_comments_submit comment_submit" type="submit">Add Comment</button>
                    </form>
                </div>
            {% endif %}
        </div>

        <div class="post_sidebar">
            <div class="sidebar_categories">
                <div class="categories_header">
                    <h3 class="">Categories</h3>
                </div>

                <div class="categories_links grid">
                    <ul>
                        {% for category in categories %}
                        <li>
                            <a class="categories_link" href="{% url 'blog:post-category' category.name %}">
                                <div class="categories_item">
                                    <h4>{{ category.name }}</h4>
                                    <span class="count_posts_badge">{{ category.posts_count }}</span>
                                </div>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

blog/templates/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Blog {% endblock title %}

{% block content %}
    <section class="blog section">
        <h2 class="section_title"> Blog</h2>
        <span class="section_subtitle">Caches in reality.</span>
        
        <div class="container blog_container grid">
            <div class="post_data">
                <div class="post_items grid">
                    {% for post in object_list %}
                    <div class="post_item">
                        <div class="post_item_img">
                            <a class="post_list_links" href="{{ post.get_absolute_url }}">
                                {% if post.header_image %}
                                <img class="" src="{{ post.header_image.url }}" alt="{{ post.header_image }}" />
                                {% else %}
                                <img class="" src="{% static 'img/defaults/noimage.png' %}" alt="noimage" >
                                {% endif %}
                            </a>
                        </div>
                        <div class="post_item_content">
                            <h1><a class="post_list_links" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h1>
                            <h4>{{ post.author }}</h4>
                            <p class="post_item_content_body">{{ post.body|truncatewords:20|safe }}</p>
                            <p class="post_item_content_date">posted on: {{ post.date|date:"SHORT_DATE_FORMAT" }}</p>
                        </div>
                    </div>
                    {% endfor %} 
                </div>
            </div>
            <div class="post_sidebar"> 
                <div class="sidebar_recent_posts">
                    <div class="recent_posts_header">
                        <h3 class="">Recent Posts</h3>
                    </div>
                    
                    {% for post in recent_posts %}
                    <div class="recent_posts_item grid">
                        <div class="rp_item_thumbnail">
                            <a href="{{ post.get_absolute_url }}">
                                {% if post.header_image %}
                                <img class="" src="{{ post.header_image.url }}" alt="{{ post.header_image }}" />
                                {% else %}
                                <img class="" src="{% static 'img/defaults/noimage.png' %}" alt="noimage" >
                                {% endif %}
                            </a>
                        </div>
                        <div class="rp_details">
                            <a href="{{ post.get_absolute_url }}">
                                <p class="rp_item_date">{{ post.date|date:"D, M d, Y"  }}</p>
                                <p class="rp_item_title">{{ post.title|truncatewords:3|safe }}</p>
                            <a href=""></a>
                        </div>
                    </div>
                    {% endfor %}
                
                </div>

                <div class="sidebar_categories">
                    <div class="categories_header">
                        <h3 class="">Categories</h3>
                    </div>

                    <div class="categories_links grid">
                        <ul>
                            {% for category in categories %}
                            <li>
                                <a class="categories_link" href="{% url 'blog:post-category' category.name %}">
                                    <div class="categories_item">
                                        <h4>{{ category.name }}</h4>
                                        <span class="count_posts_badge">{{ category.posts_count }}</span>
                                    </div>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

blog/templates/post_update.html
{% extends 'base.html' %}

{% block title %} Update Post {% endblock title %}

{% block content %}

<section class="blog section">
    <h2 class="section_title post_detail_title"> Edit Blog Post</h2>
    <!-- <span class="section_subtitle"></span> -->
    
    <div class="container blog_container grid">
        <form method="post">
            <div class=" grid">
                {% csrf_token %}
                {{ form.media }}
                {% for field in form %}
                    <div class="contact_content">
                        <label class="contact_label">{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
                <!-- {{ form.as_p }}-->
                <div class="">
                    <input class="button button--flex contact_submit" type="submit" value="Update">
                </div> 
            </div>
        </form>
    </div>
</section>


{% endblock content %}