blog/urls.py
from django.urls import path, include

from blog.models import Post
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    PostCategoryView,
    PostAddLike,
    PostAddComment,
)

app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('<int:pk>', PostDetailView.as_view(), name='post-detail'),
    path('edit/<int:pk>', PostUpdateView.as_view(), name='post-edit'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='post-delete'),
    path('create/', PostCreateView.as_view(), name='post-create'),
    path('category/<str:cats>/', PostCategoryView, name='post-category'),

    # ajax urls
    path('userlike/', PostAddLike, name='post-user-like'),
    path('usercomment/', PostAddComment, name='post-user-comment'),
]

# handler404 = 'blog.views.errorpage'
# handler500 = 'blog.views.errorpage'

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}I am Jarvis.{% endblock title %}</title>
        <!-- unicons -->
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">

        <!-- swiper css -->
        <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}" />
        
        <!-- css -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />

        
    </head>
    <body>
        {% if view.template_name != 'home.html' %}
            {% include 'blog_header.html' %}
        {% else %}
            {% include 'header.html' %}
        {% endif %}
        
        {% block content %}
        
        {% endblock content %}

        {% include 'footer.html' %}

        <a href="#" class="scrollup" id="scroll-up">
            <i class="uil uil-angle-double-up scrollup_icon"></i>
        </a>
        
        <!-- swiper js -->
        <script src="{% static 'js/swiper-bundle.min.js' %}"></script>

        <!-- sweet alert -->
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

        <!-- main js -->
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

templates/footer.html
<!-- footer -->
<footer class="footer">
    <div class="footer_bg">
        <div class="footer_container container grid">
            <div class="footer_information">
                <h1 class="footer_title">Jarvis Millan</h1>
                <span class="footer_subtitle">Web Developer</span>
            </div>

            <ul class="footer_links">
                <li>
                    <a href="#about" class="footer_link">About</a>
                </li>
                <li>
                    <a href="#services" class="footer_link">Services</a>
                </li>
                <li>
                    <a href="{% url 'blog:post-list' %}" class="footer_link">Blog</a>
                </li>
                <li>
                    <a href="#contact" class="footer_link">Contact</a>
                </li>
            </ul>

            <div class="footer_socials">
                <a href="https://www.linkedin.com/in/jarviscript/" class="footer_social">
                    <i class="uil uil-linkedin"></i>
                </a>

                <a href="https://github.com/pluckannfeel" class="footer_social">
                    <i class="uil uil-github"></i> 
                </a>

                <a href="https://www.instagram.com/millan.jarvis/" class="footer_social">
                    <i class="uil uil-instagram"></i>
                </a>
            </div>
        </div>
    </div>
</footer>

templates/header.html
<header class="header" id="header">
    <nav class="nav container">
        <a href="" class="nav_logo">Jarvis </a>
        <div class="nav_menu" id="nav-menu">
            <ul class="nav_list grid">
                <li class="nav_item">
                    <a href="#home" class="nav_link">
                        <i id="active_starter" class="uil uil-home nav_icon active-link"></i> Home
                    </a>
                </li>
                <li class="nav_item">
                    <a href="#about" class="nav_link">
                        <i class="uil uil-user-circle nav_icon"></i> About
                    </a>
                    
                </li>
                <li class="nav_item">
                    <a href="#skills" class="nav_link">
                        <i class="uil uil-wrench nav_icon"></i> Skills
                    </a>
                </li>
                <li class="nav_item">
                    <a href="#portfolio" class="nav_link">
                        <i class="uil uil-books nav_icon"></i> Portfolio
                    </a>
                </li>
                <!-- <li  class="nav_item">
                    <a href="#services" class="nav_link">
                        <i class="uil uil-bag nav_icon"></i> Services
                    </a>
                </li> -->
                <li  class="nav_item">
                    <a href="{% url 'blog:post-list' %}" class="nav_link">
                        <i class="uil uil-document-layout-left nav_icon"></i> Blog
                    </a>
                </li>
                <li  class="nav_item">
                    <a href="#contact" class="nav_link">
                        <i class="uil uil-at nav_icon"></i> Contact
                    </a>
                </li>
            </ul>

            <i class="uil uil-times nav_close " id="nav-close"></i>
        </div>

        <div class="nav_btns">
            <!-- change theme -->
            <i class="uil uil-moon change_theme" id="theme-button"></i>

            <div class="nav_toggle" id="nav-toggle">
                <i class="uil uil-apps"></i>
            </div>
        </div>
    </nav>
</header>